URL_SERVICE = "https://cnt-13a422c8-e1d0-47f6-a6de-65b7f4251098.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"